"""lesson resume position

Revision ID: f51cb58130e6
Revises: bbe1fb988adb
Create Date: 2026-08-14 13:00:16.958900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f51cb58130e6'
down_revision: Union[str, Sequence[str], None] = 'bbe1fb988adb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add resume position to lesson progress.

    server_default is required, not cosmetic: adding a NOT NULL column to a table
    that already has rows fails outright without one. Autogenerate omitted it
    because the model carries a Python-side default, which Postgres never sees.

    The default is dropped immediately afterwards so inserts keep going through
    the model rather than silently relying on the database.
    """
    op.add_column(
        "lesson_progress",
        sa.Column("position_seconds", sa.Integer(), nullable=False, server_default="0"),
    )
    op.alter_column("lesson_progress", "position_seconds", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_progress', 'position_seconds')
    # ### end Alembic commands ###
